// import { Toaster } from "sonner";
import "../../../app/globals.css";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import AppSidebar from "./@sidebar/page";

export const metadata = {
  title: "Your App",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <SidebarProvider>
        <AppSidebar />
        <SidebarInset>
          <div className="py-2 gap-2 flex sticky top-0 bg-white">
            <SidebarTrigger className="cursor-pointer" />
            <h1 className="text-lg font-medium">Dashboard</h1>
          </div>
          <div className="bg-gray-100 h-full rounded-md">{children}</div>
        </SidebarInset>
        {/* <Toaster richColors position="top-right" /> */}
      </SidebarProvider>
    </div>
  );
}
