import type { Metadata } from "next";
import "../../app/globals.css";
import { Toaster } from "sonner";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const cookie = cookieStore.get("loggedInUser");
  if (!cookie) {
    redirect("/login");
  }

  return (
    <div>
      {children}
      <Toaster position="top-center" richColors />
    </div>
  );
}
